### ISSUE TITLE
Email::Address->parse can return empty list

### ISSUE THREAD

**Issue by epa** [Perl-Email-Project/Email-Reply#3]
I spotted the warning

`Can't call method "name" on an undefined value at /usr/share/perl5/vendor_perl/Email/Reply.pm line 49.`

This is with version 1.202.  Looking at the code, it appears that _new calls Email::Address->parse, which can return an empty list, leaving $self->{to} undefined.

**Comment by epa** [comment]
Hi, do you think you will have time to look at the suggested patch?

**Comment by rjbs** [comment]
Apparently I merged this a while ago!

Email::Reply is looking for a new maintainer.
